import { CalendarEvent } from '@/types'

// Generate events across multiple months (October 2024 - March 2025)
export const sampleEvents: CalendarEvent[] = [
  // October 2024
  {
    id: '1',
    title: 'Fall Festival on Nassau Street',
    description: 'Join us for music, food trucks, and fall activities on Nassau Street!',
    category: 'social',
    date: '2024-10-15',
    startTime: '14:00',
    endTime: '18:00',
    location: 'Nassau Street',
    interestedCount: 245,
    tags: ['outdoor', 'free'],
  },
  {
    id: '2',
    title: 'CS Department Info Session',
    description: 'Learn about computer science courses and research opportunities.',
    category: 'academic',
    date: '2024-10-18',
    startTime: '16:30',
    endTime: '18:00',
    location: 'Friend Center 101',
    registrationLink: 'https://example.com/register',
    interestedCount: 189,
    tags: [],
  },
  {
    id: '3',
    title: 'Free Pizza Night',
    description: 'Free pizza for all students courtesy of the Graduate Student Government.',
    category: 'food',
    date: '2024-10-22',
    startTime: '18:00',
    endTime: '20:00',
    location: 'Frist Campus Center',
    interestedCount: 412,
    tags: ['free food', 'pizza'],
  },

  // November 2024
  {
    id: '4',
    title: 'Princeton vs Yale Game Watch Party',
    description: 'Cheer on the Tigers as we take on Yale! Snacks and drinks provided.',
    category: 'social',
    date: '2024-11-09',
    startTime: '13:00',
    endTime: '16:00',
    location: 'Frist Campus Center Multipurpose Room',
    interestedCount: 328,
    tags: ['sports', 'rivalry', 'free food'],
  },
  {
    id: '5',
    title: 'Career Fair - Tech Companies',
    description: 'Meet recruiters from top tech companies including Google, Meta, and startups.',
    category: 'career',
    date: '2024-11-12',
    startTime: '10:00',
    endTime: '16:00',
    location: 'Jadwin Gymnasium',
    registrationLink: 'https://example.com/career-fair',
    capacity: 500,
    interestedCount: 467,
    tags: ['networking', 'tech'],
  },
  {
    id: '6',
    title: 'Intro to Machine Learning Workshop',
    description: 'Hands-on workshop covering ML basics with Python and scikit-learn.',
    category: 'academic',
    date: '2024-11-14',
    startTime: '19:00',
    endTime: '21:00',
    location: 'Friend Center 008',
    interestedCount: 156,
    tags: ['workshop', 'ml', 'coding'],
  },
  {
    id: '7',
    title: 'Diwali Celebration',
    description: 'Celebrate the festival of lights with traditional food, music, and dance!',
    category: 'arts',
    date: '2024-11-16',
    startTime: '18:00',
    endTime: '21:00',
    location: 'McCosh Hall',
    interestedCount: 289,
    tags: ['cultural', 'food', 'performance'],
  },
  {
    id: '8',
    title: 'Thanksgiving Dinner',
    description: 'Traditional Thanksgiving dinner for students staying on campus.',
    category: 'food',
    date: '2024-11-23',
    startTime: '17:00',
    endTime: '20:00',
    location: 'Whitman College Dining Hall',
    interestedCount: 198,
    tags: ['free food', 'thanksgiving'],
  },
  {
    id: '9',
    title: 'Intramural Basketball Tournament',
    description: 'Annual 3v3 basketball tournament. Register your team now!',
    category: 'sports',
    date: '2024-11-20',
    startTime: '15:00',
    endTime: '18:00',
    location: 'Dillon Gym',
    registrationLink: 'https://example.com/basketball',
    capacity: 64,
    interestedCount: 87,
    tags: ['sports', 'tournament'],
  },

  // December 2024
  {
    id: '10',
    title: 'Holiday Cookie Decorating',
    description: 'Decorate holiday cookies and enjoy hot cocoa. All supplies provided!',
    category: 'social',
    date: '2024-12-05',
    startTime: '19:00',
    endTime: '21:00',
    location: 'Butler College Common Room',
    interestedCount: 145,
    tags: ['holiday', 'food', 'crafts'],
  },
  {
    id: '11',
    title: 'Finals Study Break - Free Snacks',
    description: 'Take a break from studying! Free snacks, coffee, and stress relief activities.',
    category: 'food',
    date: '2024-12-12',
    startTime: '20:00',
    endTime: '23:00',
    location: 'Firestone Library Plaza',
    interestedCount: 512,
    tags: ['free food', 'study break', 'finals'],
  },
  {
    id: '12',
    title: 'Winter Concert - Princeton University Orchestra',
    description: 'Annual winter concert featuring classical and contemporary pieces.',
    category: 'arts',
    date: '2024-12-08',
    startTime: '20:00',
    endTime: '22:00',
    location: 'Richardson Auditorium',
    interestedCount: 234,
    tags: ['music', 'concert', 'classical'],
  },

  // January 2025
  {
    id: '13',
    title: 'New Year Kickoff Party',
    description: 'Welcome back to campus! Games, music, and food to start the semester.',
    category: 'social',
    date: '2025-01-25',
    startTime: '19:00',
    endTime: '23:00',
    location: 'Frist Campus Center',
    interestedCount: 378,
    tags: ['party', 'music', 'free food'],
  },
  {
    id: '14',
    title: 'Spring Semester Course Shopping',
    description: 'Information session about popular spring courses and registration tips.',
    category: 'academic',
    date: '2025-01-28',
    startTime: '16:00',
    endTime: '17:30',
    location: 'McCosh 50',
    interestedCount: 267,
    tags: ['advising', 'courses'],
  },
  {
    id: '15',
    title: 'Yoga and Meditation Session',
    description: 'Start your semester with mindfulness. All levels welcome!',
    category: 'sports',
    date: '2025-01-30',
    startTime: '08:00',
    endTime: '09:00',
    location: 'Dillon Gym Studio',
    interestedCount: 89,
    tags: ['wellness', 'fitness'],
  },

  // February 2025
  {
    id: '16',
    title: 'Valentine\'s Day Dance',
    description: 'Celebrate with friends! DJ, photo booth, and Valentine\'s themed snacks.',
    category: 'social',
    date: '2025-02-14',
    startTime: '21:00',
    endTime: '01:00',
    location: 'Terrace Club',
    interestedCount: 423,
    tags: ['dance', 'party', 'valentine'],
  },
  {
    id: '17',
    title: 'Startup Pitch Competition',
    description: 'Watch student startups pitch their ideas. $10k prize pool!',
    category: 'career',
    date: '2025-02-20',
    startTime: '18:00',
    endTime: '21:00',
    location: 'Friend Center Auditorium',
    interestedCount: 312,
    tags: ['entrepreneurship', 'competition'],
  },
  {
    id: '18',
    title: 'Lunar New Year Celebration',
    description: 'Ring in the Year of the Snake with performances, food, and festivities!',
    category: 'arts',
    date: '2025-02-01',
    startTime: '18:00',
    endTime: '22:00',
    location: 'Frist Campus Center',
    interestedCount: 445,
    tags: ['cultural', 'performance', 'food'],
  },

  // March 2025
  {
    id: '19',
    title: 'Spring Break Housing Swap',
    description: 'Looking to trade or sublet your room for spring break? Meet potential swappers!',
    category: 'housing',
    date: '2025-03-05',
    startTime: '17:00',
    endTime: '19:00',
    location: 'Frist Campus Center 302',
    interestedCount: 67,
    tags: ['housing', 'spring break'],
  },
  {
    id: '20',
    title: 'Research Symposium',
    description: 'Undergraduate research presentations across all disciplines.',
    category: 'academic',
    date: '2025-03-15',
    startTime: '09:00',
    endTime: '17:00',
    location: 'Friend Center',
    interestedCount: 234,
    tags: ['research', 'presentations'],
  },
  {
    id: '21',
    title: 'St. Patrick\'s Day 5K Run',
    description: 'Wear green and run for a cause! All proceeds benefit local charities.',
    category: 'sports',
    date: '2025-03-17',
    startTime: '07:00',
    endTime: '09:00',
    location: 'Carnegie Lake',
    registrationLink: 'https://example.com/5k',
    interestedCount: 156,
    tags: ['running', 'charity', 'outdoor'],
  },
  {
    id: '22',
    title: 'Free Bagel Breakfast',
    description: 'Start your Monday right with free bagels, cream cheese, and coffee!',
    category: 'food',
    date: '2025-03-10',
    startTime: '08:00',
    endTime: '10:00',
    location: 'Frist Campus Center',
    interestedCount: 389,
    tags: ['free food', 'breakfast'],
  },
  {
    id: '23',
    title: 'Spring Musical Auditions',
    description: 'Audition for this year\'s spring musical production!',
    category: 'arts',
    date: '2025-03-22',
    startTime: '14:00',
    endTime: '18:00',
    location: 'Mathey College Theatre',
    interestedCount: 78,
    tags: ['theatre', 'auditions', 'musical'],
  },

  // Additional November events (to make November fuller)
  {
    id: '24',
    title: 'Python for Data Science Workshop',
    description: 'Learn pandas, numpy, and data visualization techniques.',
    category: 'academic',
    date: '2024-11-05',
    startTime: '18:00',
    endTime: '20:00',
    location: 'Lewis Library 138',
    interestedCount: 167,
    tags: ['workshop', 'python', 'data science'],
  },
  {
    id: '25',
    title: 'Late Night Pancakes',
    description: 'Midnight pancakes to fuel your late-night studying!',
    category: 'food',
    date: '2024-11-18',
    startTime: '23:00',
    endTime: '01:00',
    location: 'Whitman College Dining',
    interestedCount: 234,
    tags: ['free food', 'late night'],
  },
  {
    id: '26',
    title: 'Alumni Networking Event',
    description: 'Meet Princeton alumni working in finance, consulting, and tech.',
    category: 'career',
    date: '2024-11-21',
    startTime: '17:00',
    endTime: '19:00',
    location: 'Prospect House',
    registrationLink: 'https://example.com/alumni',
    interestedCount: 203,
    tags: ['networking', 'alumni'],
  },
  {
    id: '27',
    title: 'Movie Night: Princeton Classics',
    description: 'Watch classic films shot on Princeton\'s campus with free popcorn!',
    category: 'social',
    date: '2024-11-06',
    startTime: '20:00',
    endTime: '23:00',
    location: 'McCosh 50',
    interestedCount: 145,
    tags: ['movie', 'film', 'free food'],
  },
  {
    id: '28',
    title: 'Trivia Night',
    description: 'Form teams and compete for prizes! Categories include pop culture, history, and science.',
    category: 'social',
    date: '2024-11-19',
    startTime: '20:00',
    endTime: '22:00',
    location: 'Frist Campus Center',
    interestedCount: 198,
    tags: ['trivia', 'competition', 'games'],
  },
]
